# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: add_admin # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # NEWS
  - name: "news" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "News" # Used in the UI, ie.: "New Post"
    folder: "_news" # The path to the folder where the documents are stored
    sort: "date:asc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Full Text", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Thumbnail Image (92 x 60 / 72DPI to 96DPI)", name: "thumbnail", widget: "image"}
      - {label: "Featured Image (500 x 333 / 72DPI to 96DPI)", name: "featuredpict", widget: "image", required: false}
      - label: "Author"
        name: "author"
        widget: "select"
        options:
          - { label: "Direction", value: "direction" }
          - { label: "Stephanie Duquet", value: "stephanie_duquet" }
          - { label: "Marc-André Daigle", value: "marc_andre_daigle" }
          - { label: "Steven Dopheide", value: "steven_dopheide" }
          - { label: "Student's Life", value: "student_life" }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:MM:ss"}
      - {label: "Short Publish Date", name: "shortdate", widget: "date", format: "YYYY-MM-DD", required: false}
      - {label: "Categories", name: "categories", widget: "string", required: false}
  # EVENTS OF THE MONTH
  - name: "event" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Event" # Used in the UI, ie.: "New Post"
    folder: "_events" # The path to the folder where the documents are stored
    sort: "date:asc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
      - {label: "Year", name: "event_year", widget: "string", required: true}
      - {label: "Month", name: "event_month", widget: "select", options: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"], required: true}
      - {label: "Date", name: "event_date", widget: "number", required: false}
      - {label: "Title", name: "title", widget: "string", tagname: "h1", required: true}
      - {label: "Small Description", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Thumbnail Image (80 x 80 / 72DPI to 96DPI)", name: "thumbnail", widget: "image"}
      - {label: "URL of the event", name: "url", widget: "string"}
      - label: "Author"
        name: "author"
        widget: "select"
        options:
          - { label: "Direction", value: "direction" }
          - { label: "Stephanie Duquet", value: "stephanie_duquet" }
          - { label: "Marc-André Daigle", value: "marc_andre_daigle" }
          - { label: "Steven Dopheide", value: "steven_dopheide" }
          - { label: "Student's Life", value: "student_life" }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:MM:ss"}
      - {label: "Categories", name: "categories", widget: "string", required: false}
  # SLIDER
  - name: "slider" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Slide" # Used in the UI, ie.: "New Post"
    folder: "_slider" # The path to the folder where the documents are stored
    sort: "date:asc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields each document in this collection have
      - {label: "Layout", name: "layout", widget: "hidden", default: "home"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Middle small text", name: "intro_paragraph", widget: "markdown", required: false}
      - {label: "Button Label (text on button)", name: "buttonlabel", widget: "string"}
      - {label: "Button URL", name: "url", widget: "string"}
      - label: "Author"
        name: "author"
        widget: "select"
        options:
          - { label: "Direction", value: "direction" }
          - { label: "Stephanie Duquet", value: "stephanie_duquet" }
          - { label: "Marc-André Daigle", value: "marc_andre_daigle" }
          - { label: "Steven Dopheide", value: "steven_dopheide" }
          - { label: "Student's Life", value: "student_life" }
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:MM:ss"}
      - {label: "Featured Image (1920 x 978 / 72DPI to 96DPI)", name: "featuredpict", widget: "image"}
      - {label: "Categories", name: "categories", widget: "string", required: false}